export UPSTREAM_GERRIT_HOST_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDOoBwcqoJy2G0FiuUG7aj5/uHfSPXItvfKpCVS8dHTXW+Yxgs5DG9PsS/7PfX/eaji3JjZjjtB45wjcVTvt89+sFsTLNdMCCnalwlRuLW6qoWJC5tmR0Yt5FiFZzOXOgP1Y1to1zbX1gwVsnohMKP950YKhSTcHCElH6iYy9AZHQ== root@ci-base-image"
export GIT_EMAIL='kepeng1314@gmail.com'
export GIT_NAME='MyVendor Jenkins'
export UPSTREAM_GERRIT_USER=patrickke
export UPSTREAM_GERRIT_SSH_KEY_PATH=gerrit_key
export JENKINS_SSH_KEY_PATH=jenkins_key
export PUBLISH_HOST=127.0.0.1
